language: java
sudo: false
install: true

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "annimon-github"

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.sonar/cache

before_install:
 - chmod +x gradlew
 
after_success:
 - ./gradlew proguard sonarqube
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "latest" && curl -F "file=@store/OwnLang.jar" http://projects.annimon.com/samples/php/travis/upload.php?mode=ownlang
